# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fba737fe5854ac78589df4e1bb964030d438ff90ba8ba65fc89bc74c64c3fb3828d5172d68474e093c77a36269c897ca6e4455dc231e5da4896f64419add237

test:
  secret_key_base: 029347e77096e21558ba6b171be5e58f12eb49d7ddd12a634a0cb58ca9dd5d5d0cba5d65be46620225e0dfa0ceb30c3ca984d42c07aac792a7636e9c7c2b4678

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
